config/routes.rb
Rails.application.routes.draw do
    resources :generos
    get "filmes/busca", to: "filmes#busca", as: :busca_filme
    get "filmes/minha_lista", to: "filmes#minha_lista", as: :minha_lista
    post "filmes", to: "filmes#create"
    resources :filmes, only: [:new, :destroy, :edit, :update, :index]
    root to: "filmes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/filme.rb
class Filme < ApplicationRecord


    belongs_to :genero, optional: true
    validates :titulo, :genero, presence: true
    validates :atorprincipal, length: {minimum:4}

    def status_message
        if status == "assisti"
            return "Já assisti"
        
        elsif status == "quero_ver"
            return "Quero Assistir"
        
        else 
            return 
            
        end

    end
end

app/models/genero.rb
class Genero < ApplicationRecord
    validates :nome, length: {minimum:4}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/filmes_controller.rb
class FilmesController < ApplicationController

    attr_accessor :status

    
    before_action :set_filme, only: [:edit, :update, :destroy]
    
    def index 
        @filmes = Filme.order :nota
         
    end 

    def new
        @filme = Filme.new
        @generos = Genero.all
    end

    def edit
       renderiza :new
    
    end

    def create
        @filme = Filme.new filme_params
        if @filme.save
            flash[:notice] = "Filme salvo com sucesso!"
            redirect_to root_path
        else
            renderiza :new
        end
    end
    
    def destroy
        @filme.destroy
        redirect_to root_path
    end 

    def update 
        if @filme.update filme_params
            flash[:notice] = "Filme atualizado com sucesso!"
            redirect_to root_path
        else
            renderiza :edit
        end
    end

    def busca
        @titulo = params[:titulo]
        @filmes = Filme.where "titulo like ?", "%#{@titulo}%"
    end


    def minha_lista
        @status = params[:status]
        @filme = Filme.where (status == "quero_ver")
    end 


    private

    def filme_params
        params.require(:filme).permit(:titulo,
        :atorprincipal, :nota, :ano, :genero_id, :status)
    
    end
    
    def set_filme
        @filme = Filme.find(params[:id])
    end

    def renderiza(view)
        @generos = Genero.all
        render view
    end

end

app/controllers/generos_controller.rb
class GenerosController < ApplicationController
  before_action :set_genero, only: [:show, :edit, :update, :destroy]

  # GET /generos
  # GET /generos.json
  def index
    @generos = Genero.all
  end

  # GET /generos/1
  # GET /generos/1.json
  def show
    @filmes_por_genero = Filme.where("genero_id = ?", params[:id])
  end

  # GET /generos/new
  def new
    @genero = Genero.new
  end

  # GET /generos/1/edit
  def edit
  end

  # POST /generos
  # POST /generos.json
  def create
    @genero = Genero.new(genero_params)
    respond_to do |format|
      if @genero.save
        format.html { redirect_to generos_url, notice: 'Gênero criado com sucesso.' }
        format.json { render :show, status: :created, location: @genero }
      else
        format.html { render :new }
        format.json { render json: @genero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /generos/1
  # PATCH/PUT /generos/1.json
  def update
    respond_to do |format|
      if @genero.update(genero_params)
        format.html { redirect_to @genero, notice: 'Gênero Atualizado.' }
        format.json { render :show, status: :ok, location: @genero }
      else
        format.html { render :edit }
        format.json { render json: @genero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /generos/1
  # DELETE /generos/1.json
  def destroy
    @genero.destroy
    respond_to do |format|
      format.html { redirect_to generos_url, notice: 'Gênero deletedado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genero
      @genero = Genero.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genero_params
      params.require(:genero).permit(:nome)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/filmes_helper.rb
module FilmesHelper
end

app/helpers/generos_helper.rb
module GenerosHelper
end

app/views/filmes/_filme.html.erb
<div style= background-color:red>
<tr>
    <td><%= filme.titulo %></td>
    <td><%= filme.atorprincipal %></td>
    <td><%= filme.ano %></td>
    <td><%= filme.genero.nome unless filme.genero.nil? %></td>
    <td><%= filme.status_message %></td>
    <td><%= link_to "Editar", edit_filme_path(filme), class: "btn btn-default" %> </td>
    <td><%= button_to "Deletar", filme, method: :delete, class:"btn btn-danger", data: {confirm: "Tem certeza que deseja deletar o filme #{filme.titulo}?"} %></td>
</tr>
<div>

app/views/filmes/_form.html.erb
<% @filme.errors.full_messages.each do |msg| %>
<div class="alert alert-danger" role="alert">
    <%= msg %>
</div>
<% end %>
    <%= form_for @filme do |form|%>
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <%= form.label :título %>
                <%= form.text_field :titulo, class:"form-control" %>
                
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <%= form.label "Diretor(a)" %>
                <%= form.text_field :atorprincipal, class:"form-control"%>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-2">
            <div class="form-group">
                <%= form.label :ano %>
                <%= form.number_field :ano, class:"form-control"%>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-2">
            <div class="form-group">
                <%= form.label :genêro %>
                <%= form.collection_select(:genero_id, Genero.all, :id, :nome, class:"form-control", style:"color:red") %>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-6"> 
            <%= form.label :status %>
            <div class="form-check">
                <%= form.radio_button(:status, "assisti", class: "form-check-input") %>
                <%= label_tag(:status_assistido, "Já assisti", class: "form-check-label") %><p>
                <%= form.radio_button(:status, "quero_ver", class: "form-check-input") %>
                <%= label_tag(:status_minha_lista, "Quero Ver", class: "form-check-label") %><p>
            </div>
        </div>
    </div>

        <%= form.submit texto_da_acao, class:"btn btn-primary"%>

    <% end %>

app/views/filmes/busca.html.erb
<table class="table table-bordered table-dark", style="background-color: #333333">
    <thead>
        <tr>
            <td><h3>Titulo</td>
            <td><h3>Diretor(a)</td>
            <td><h3>Nota</td>
            <td><h3>Gênero </td>
            <td><h3>Status </td>
            <td colspan="2">
        </tr>
    </thead>
    <tbody>
        <%= render @filmes %>
    </tbody>
</table>

app/views/filmes/edit.html.erb
<%= render partial: "form", locals: {texto_da_acao: "Atualizar"} %>

app/views/filmes/index.html.erb
<% if flash[:notice]%>
    <div class="alert alert-success" role="alert">
        <%= flash[:notice] %>
    </div>
<%end%>


<table class="table table-bordered table-dark">
    <div>
        <img src="https://i.imgur.com/mjT3igf.png" height="250" width="1140" alt="Imagem de mãos e sangue"><p>
    </div>
    <thead>
        <tr>
            <td><h3><b>Título</b></h3></td>
            <td><h3 >Diretor(a)</h3></td>
            <td><h3>Ano</h3></td>
            <td><h3>Gênero</h3></td>
            <td><h3>Status</h3></td> 
            <td colspan="2">
        </tr>
    </thead>
    <tbody>
        <%= render @filmes %>

app/views/filmes/minha_lista.html.erb
<div class="box2">
    <h3>Minha Lista<h3><p>
</div>

<table class="table table-bordered table-dark">
    <thead>
        <tr>
            <td><h3>Título</h3></td>
            <td><h3 >Ator Principal</h3></td>
            <td><h3>Ano</h3></td>
            <td><h3>Gênero</h3></td>
            <td colspan="2">
           
        </tr>
    </thead>

    <tbody>
        <% @filme.each do |filme| %>
        <%if (filme.status == "quero_ver")%>
            <tr>
                <td><%= filme.titulo %></td>
                <td><%= filme.atorprincipal %></td>
                <td><%= filme.ano %></td>
                <td><%= filme.genero.nome unless filme.genero.nil? %></td>
                <td><%= link_to "Editar", edit_filme_path(filme), class: "btn btn-default" %> </td>
            
            </tr>
        
        <%end%>
        <%end%>
    </tbody>
</table>

app/views/filmes/new.html.erb
<%= render partial: "form", locals: {texto_da_acao: "Salvar"} %>

app/views/generos/_form.html.erb
<%= form_with(model: genero, local: true) do |form| %>
  <% if genero.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(genero.errors.count, "error") %> Esse gênero não pode ser salvo</h2>

      <ul>
        <% genero.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row" >
    <div class="col-sm-2">
      <%= form.label :nome, style:"font-size: 20px" %>
      <%= form.text_field :nome %><p>
    </div>
  </div>

    <%= form.submit "Adicionar", class:"btn btn-primary", style:"background-color:#404040" %><p>
 
<% end %>

app/views/generos/edit.html.erb
<h1> Gênero</h1>

<%= render 'form', genero: @genero %>

<%= link_to 'Ver Filmes', @genero %> |
<%= link_to 'Voltar', generos_path, style:"color: red; font-size: 14px;" %>

app/views/generos/index.html.erb
<p id="notice"><%= notice %></p>
<div class="box2">
    <h3>Gêneros<h3><p>
</div>

<div class = "box1">
  <table class="table table-bordered table-dark">
    <thead>
      <tr>
        <th><h3 style="font-size:200%; font-family:verdana; color:#f2f2f2;">Nome</h3></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @generos.each do |genero| %>
        <tr>
          <td><%= genero.nome %></td>
          <td><%= link_to 'Ver Filmes', genero, class: "btn btn-default" %></td>
          <td><%= link_to 'Editar', edit_genero_path(genero), class: "btn btn-default" %></td>
          <td><%= link_to 'Deletar', genero, method: :delete, data: { confirm: 'Tem certeza que deseja deletar?' }, class: "btn btn-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
<br>

<%= link_to 'Adicionar novo Genero', new_genero_path, class: "btn btn-default", style:"background-color: #d9d9d9" %>

app/views/generos/new.html.erb
<div class="box2">
    <h3>Novo Gênero<h3><p>
</div>

<%= render 'form', genero: @genero %>

<%# <%= link_to 'Voltar', generos_path %>

app/views/generos/show.html.erb
<div class = "box3">
<table class="table table-bordered">
    <thead>
        <tr>
            <td><h3>Título</h3></td>
            <td><h3>Diretor(a)</h3></td>
            <td><h3>Ano</h3></td>
            <td><h3>Gênero</h3></td>
            <td><h3>Status</h3></td>
            <td colspan="2">
        </tr>
    </thead>
    <tbody>
        <%= render @filmes_por_genero %>
    </tbody>
</table>
</div>
<%= link_to 'Voltar', generos_path, class: "btn btn-default" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The movies list</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= nav_bar brand: "Filmes", class:"navbar navbar-expand-lg", brand_link: root_url do %>
        <%= menu_group do %>
        <%= menu_item "Adicionar um novo filme", new_filme_path %>
        <%= menu_item "Genêros", generos_path %>
        <%= menu_item "Minha Lista", minha_lista_path %>
      <%end%>
      <%= form_tag busca_filme_path, method: :get, class:"navbar-form navbar-right" do %>
      <div class="form-group">
        <%= text_field_tag :titulo, @titulo, class: "from-control"%>
        <%= button_to "Buscar", nil, class:"btn btn-default"%>    
      </div>
      <%end%>
    <%end%>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>